version: '3.8'

services:
  backend:
    build: ./back
    container_name: snake-game-backend
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS}
      - CORS_ALLOW_METHODS=${CORS_ALLOW_METHODS}
      - CORS_ALLOW_HEADERS=${CORS_ALLOW_HEADERS}
    networks:
      - app-network

  frontend:
    build: ./front
    container_name: snake-game-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: snake-game-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 